### ISSUE TITLE
The allocator cannot be signing

### ISSUE THREAD

**Issue by herony-fil** [fidlabs/allocator-tooling#118]
The allocator cannot be signing    

https://allocator.tech/application/herony-fil/herony-data-pathway/f1t7xoprasdswrd73egve2yut67im5zedjoyu7mly

![Image](https://github.com/user-attachments/assets/b18f1585-2e17-4538-9d63-e9ccfd305ba7)

**Comment by kacperzuk-neti** [comment]
Which version of the Filecoin App do you have installed on your Ledger wallet?

**Comment by herony-fil** [comment]
v0.24.2

**Comment by herony-fil** [comment]
The Filecoin App version on Ledger wallet has been upgraded to v2.0.1. However, when connecting Ledger, it always prompts "Please update Filecoin app on Ledger."

![Image](https://github.com/user-attachments/assets/ef168c73-d245-4f74-bb56-b782ef571071)

**Comment by Filip-L** [comment]
@herony-fil, The issue should be solved now. Please let me know if everything is working correctly.

**Comment by herony-fil** [comment]
@Filip-L  Thanks, I tried it, and it can be connected to the Ledger, but the signature still encounters the same error as before

![Image](https://github.com/user-attachments/assets/c663450f-cad1-4020-940e-5f37394cd6ab)

**Comment by Filip-L** [comment]
@herony-fil, could you please tell me which browser and version you're using? Also, could you try to grant DataCap in incognito mode with all extensions disabled, and let me know if the issue persists?

**Comment by herony-fil** [comment]
@Filip-L Thank you so much! After updating to the latest version of Chrome and with no extensions loaded, the signature worked successfully. Thanks again!
